package org.acme.repository;


import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import org.acme.model.DTO.UsuarioDTO;
import org.acme.model.Usuario;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;


@ApplicationScoped
public class UsuarioRepository {


    /*CREATE TABLE T_RHSTU_PACIENTE (
    id_paciente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_paciente VARCHAR(90),
    cpf VARCHAR(20),
    nr_telefone_paciente VARCHAR(20),
    email_paciente VARCHAR(100),
    senha_paciente VARCHAR(60)
);
    */

    @Inject
    DataSource dataSource;

    public void inserirPaciente(UsuarioDTO usuario){
        String sqlI = "INSERT INTO T_RHSTU_PACIENTE (nm_paciente, cpf, nr_telefone_paciente, email_paciente, senha_paciente) VALUES (?,?,?,?,?)";
            try (Connection con = dataSource.getConnection();
                 PreparedStatement ps = con.prepareStatement(sqlI)
            ) {
                ps.setString(1, usuario.getNome_usuario());
                ps.setString(2, usuario.getCpf());
                ps.setString(3, usuario.getTelefone());
                ps.setString(4, usuario.getEmail_usuario());
                ps.setString(5, usuario.getSenha_usuario());
                ps.executeUpdate();
            } catch (SQLException e){
                throw new RuntimeException("Erro de executar o cadastro.");
            }
        }
        public boolean existeId(int id){
            String sql="SELECT COUNT(*) FROM T_RHSTU_PACIENTE WHERE id_paciente=?";
            try(Connection con=dataSource.getConnection();
                PreparedStatement ps=con.prepareStatement(sql)) {
                ps.setInt(1,id);
                try(ResultSet rs= ps.executeQuery()){
                    return (rs.next() && rs.getInt(1)>0);
                }
            } catch (SQLException e) {
                throw new RuntimeException(e);
            }
        }
        public boolean existeEmail(String email_usuario){
            String sql="SELECT COUNT(*) FROM T_RHSTU_PACIENTE WHERE email_paciente=?";
            try(Connection con=dataSource.getConnection();
                PreparedStatement ps=con.prepareStatement(sql)) {
                ps.setString(1,email_usuario);
                try(ResultSet rs= ps.executeQuery()){
                    return (rs.next() && rs.getInt(1)>0);
                }
            } catch (SQLException e) {
                throw new RuntimeException(e);
            }
        }
        public boolean existeCpf(String cpf){
            String sql="SELECT COUNT(*) FROM T_RHSTU_PACIENTE WHERE cpf=?";
            try(Connection con=dataSource.getConnection();
                PreparedStatement ps=con.prepareStatement(sql)) {
                ps.setString(1,cpf);
                try(ResultSet rs= ps.executeQuery()){
                    return (rs.next() && rs.getInt(1)>0);
                }
            } catch (SQLException e) {
                throw new RuntimeException(e);
            }
        }

        public List<Usuario> RelatorioPaciente( String email_u, String senha_u) {
            String sql = "select * from T_RHSTU_PACIENTE WHERE email_paciente=? AND senha_paciente=?";

            try (Connection con = dataSource.getConnection();
                 PreparedStatement ps = con.prepareStatement(sql)) {

                ps.setString(1,email_u);
                ps.setString(2,senha_u);

                List<Usuario> l = new ArrayList<>();
                try(ResultSet rs = ps.executeQuery()) {
                    while (rs.next()) {
                        Usuario usuario = new Usuario();
                        usuario.setId_usuario(rs.getInt(1));
                        usuario.setNome_usuario(rs.getString(2));
                        usuario.setCpf(rs.getString(3));
                        usuario.setTelefone(rs.getString(4));
                        usuario.setEmail_usuario(rs.getString(5));
                        usuario.setSenha_usuario(rs.getString(6));

                        l.add(usuario);
                    }
                    return l;
                }
                }catch (SQLException e) {
                    throw new RuntimeException(e);
            }

    }
    public List<Usuario> lista() throws SQLException{
        String sql="SELECT * FROM T_RHSTU_PACIENTE ORDER BY id_paciente";
        try(Connection con= dataSource.getConnection();
            PreparedStatement ps= con.prepareStatement(sql)) {

            List<Usuario>listaUsuario= new ArrayList<>();
            try(ResultSet rs=ps.executeQuery()){
                while (rs.next()){
                    Usuario u= new Usuario();
                    u.setId_usuario(rs.getInt(1));
                    u.setNome_usuario(rs.getString(2));
                    u.setCpf(rs.getString(3));
                    u.setTelefone(rs.getString(4));
                    u.setEmail_usuario(rs.getString(5));
                    u.setSenha_usuario(rs.getString(6));

                    listaUsuario.add(u);
                }
            }
            return listaUsuario;
        }
    }


        public void RemoverPaciente(int id,String email_u, String senha_u) {
        String sql = "DELETE FROM T_RHSTU_PACIENTE WHERE id_paciente=? AND email_paciente=? AND senha_paciente=?";
                try (Connection con = dataSource.getConnection();
                     PreparedStatement ps = con.prepareStatement(sql)) {
                    ps.setInt(1,id);
                    ps.setString(2,email_u);
                    ps.setString(3,senha_u);

                    int deleta=ps.executeUpdate();
                    if (deleta>0){
                        throw new SQLException("Foi deletado");
                    }
                }catch (SQLException e) {
                    throw new RuntimeException("Erro de remover");
                }
            }


        public void updanteUsuario(int id, String nome,String cpf, String telefone, String email, String senha){
            String sql="UPDATE T_RHSTU_PACIENTE SET nm_paciente= ?, cpf= ?, nr_telefone_paciente= ?, email_paciente= ?, senha_paciente= ? WHERE id_paciente= ?";
            try(Connection con= dataSource.getConnection();
                PreparedStatement ps= con.prepareStatement(sql))
            {

                ps.setString(1,nome);
                ps.setString(2,cpf);
                ps.setString(3, telefone);
                ps.setString(4, email);
                ps.setString(5,senha);
                ps.setInt(6, id);

                int alteradas=ps.executeUpdate();
                if (alteradas==0){
                    throw new SQLException("Não atualizou");
                }

            }catch (SQLException e){
                throw new RuntimeException("Erro de executar updante.");
            }
        }
}
